[tool.poetry]
name = "wombo"
version = "0.1.71"
description = "Dream api"
authors = ["Aleksey Baev <skinxedovich@vk.com>"]
license = "mit"
readme = "README.md"
repository = "https://github.com/pokedim13/WOMBO"

[tool.poetry.dependencies]
python = "^3.8"
httpx = "^0.24.1"
pillow = "^9.5.0"
pydantic = "^1.10.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
