[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "abmatrix"
version = "0.1.5"
authors = [
  { name="Daniel Garrigan", email="popgendad@proton.me" },
]
description = "Python module to read and parse AB Matrix files"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/wisdomhealth-inc/abmatrix"
