[tool.poetry]
name = "AlekSIS-App-Paweljong"
version = "1.13.0"
packages = [
    { include = "aleksis" }
]
readme = "README.rst"
include = ["CHANGELOG.rst", "LICENCE.rst", "aleksis/**/*.mo"]

description = "AlekSIS (School Information System) — App Paweljong (Camp/Event management)"
authors = ["Tom Teichler <tom.teichler@teckids.org>", "Dominik George <dominik.george@teckids.org>"]
license = "EUPL-1.2-or-later"
homepage = "https://hacknfun.camp"
repository = "https://edugit.org/Teckids/hacknfun/AlekSIS-App-Paweljong"
classifiers = [
    "Environment :: Web Environment",
    "Intended Audience :: Education",
    "Topic :: Education"
]

[[tool.poetry.source]]
name = "gitlab"
url = "https://edugit.org/api/v4/projects/461/packages/pypi/simple"
secondary = true

[tool.poetry.dependencies]
python = "^3.9"
aleksis-core = "^2.12.2"
django-iban-field = "^0.8"
django-formtools = "2.3"
django-starfield = "^1.0"
aleksis-app-postbuero = "1.0+20220218233830.a212f707"
aleksis-app-tezor = "^1.0"

[tool.poetry.dev-dependencies]
aleksis-builddeps = "*"

[tool.poetry.plugins."aleksis.app"]
paweljong = "aleksis.apps.paweljong.apps:DefaultConfig"

[tool.black]
line-length = 100
exclude = "/migrations/"

[tool.curlylint.rules]
aria_role = true
django_forms_rendering = true
image_alt = true
indent = 2
meta_viewport = true
no_autofocus = true
tabindex_no_positive = true

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.masonry.api"
