[tool.poetry]
name = "text-emotion"
version = "0.0.2"
description = "Multilingual Emotion Classification"
authors = ["ma2za <mazzapaolo2019@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{ include = "text_emotion", from = "src" }]

repository = "https://github.com/ma2za/text-emotion"
homepage = "https://github.com/ma2za/text-emotion"

keywords = ["text-emotion", "xlm-roberta", "text-classification", "multilingual"]

[tool.poetry.dependencies]
python = "^3.8"
torch = "^2.0.1"
transformers = "^4.29.2"
requests = "^2.31.0"
easynmt = "^2.0.2"
fasttext = "^0.9.2"

[tool.poetry.group.dev.dependencies]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
