[build-system]
requires = ['setuptools>=42']
build-backend = 'setuptools.build_meta'

[project]
name = "defillamaAPI"
version = "0.0.2"
authors = [
  { name="Jafar Sadiq", email="jsadiqk92@gmail.com" },
]
description = "defillama API Module"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jafark92/defillamaAPI"
"Bug Tracker" = "https://github.com/jafark92/defillamaAPI/issues"