[tool.poetry]
name = "monday_sdk"
version = "1.0.1"
description = ""
authors = ["Jonathan Crum <jcrum@theobogroup.com>"]
readme = "README.md"
repository = "https://github.com/krummja/MondaySDK.git"
classifiers = [
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.11',
    'Operating System :: OS Independent',
    'Programming Language :: Python :: Implementation :: CPython'
]
include = [
    "README.md",
    "LICENSE.txt"
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.88.0"
pendulum = "^2.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
