[tool.poetry]
name = "classwork"
version = "0.0.3"
description = "A simple Python module to help distribute you tasks across multiple brokers as microservices"
authors = ["Anthony Mugendi <ngurumugz@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
numpy = "1.23.5"
nats-py = "2.2.0"
hashids = "1.3.1"
typjson = "0.0.32"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
