[tool.poetry]
name = "recognize"
version = "0.1.5"
description = "CLI for ML Pipeline"
authors = ["Oscar King <oscarking.nl@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
recognize = "recognize.main:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = { extras = ["all"], version = "^0.9.0" }
httpx = "^0.24.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
